#!/usr/bin/env bash


navigate() {
    sleep 5
    open "http://localhost:8888"
}

jupyter_subcmd() {

    lang=$1
    image=butuzov/jupyter


    # navigate &
    # docker run --rm -p 8888:8888 -v $(pwd):/share $imag


    case "$1" in
        "ls")
            docker images | grep butuzov/jupyter | awk '{print $1}'
            return
        ;;

        *)

            image=butuzov/jupyter

            if [[ ! -z $1 ]]; then
                image=$(printf "%s-%s" $image $lang)
            fi


            navigate &
            docker run -it --rm -p 8888:8888 -v $(pwd):/share $image
        ;;
    esac


}


jupyter_subcmd $@
