#!/usr/bin/env bash

# vsc code runner for go files and running them with cmd+r

runme_go(){
    FILE="${1}"
    if [[ "${FILE}" =~ "_test.go" ]]; then
        cd "$(dirname "${FILE}")"

        TESTS=$(cat "${FILE}" \
            | grep --color=none  -e "^func Test" \
            | sed -n 's/func \(.*\)(.*/\1/p'| xargs | sed 's/ /|/g')

        go test -v \
                -timeout=30s \
                -p=4 \
                -count=1 \
                -parallel=1 \
                -run "$TESTS"

                # -race \
        exit $?
    fi

    if [[ $(basename "${FILE}") == "main.go" ]]; then

        cd "$(dirname "${FILE}")"
        go run .
        exit $?
    fi

    go run "${FILE}"
    exit $?
}

runme_go $1
