#!/usr/bin/env bash

source "bash/funcs.sh"

header "# Activation Procedure Triggered"
install_brew
install_brew coreutils

# global .general bashrc
header "# .bashrc installation"
NWD=$(dirname $(realpath $0))
DOTS_PATH=$NWD
install_bashrc
source $NWD/.bashrc

# global .editorconfig
header "# Development"
install_dot .editorconfig

# git and related configs
header "# Git"
install_brew git
message 2 "$( printf "installed: %s " "$(git version)" )"
install_dot .gitconfig
install_dot .gitignore_global
install_dot .gitattributes
install_dot .gitmessage


# PHP && Tooling
header "# PHP"
install_brew php
message 2 "$( printf "installed: %s " "$(php -version | head -n 1)" )"
install_php_tooling

# Go & Tooling
header "# Go"
install_brew go
message 2 "$( printf "installed: %s " "$(go version)" )"

# Python & Tooling
header "# Python"
install_brew python
message 2 "$( printf "installed: %s " "$(python3 -V)" )"
install_python_tooling

# nodejs
install_brew nodejs
message 2 "$( printf "installed: %s " "$(node -v)" )"
install_nodejs_tooling

# vim settings & initial Vundle.vim
header "# vim"
install_brew vim
install_dot .vimrc
install_git_repository "https://github.com/VundleVim/Vundle.vim" \
						"vim/bundle/Vundle.vim"

header "# DevOps tooling"
install_brew terraform
install_brew nomad
install_brew consul
install_brew vault
install_brew packer
brew cask install vagrant

# Kubernetes

# Additional Tools
brew cask install vmware-fusion virtualbox sourcetree iina

# install_kube
install_brew kubectl
install_brew kubeless
install_brew jq
install_brew htop

# # additional software
header "# Additional Software"
install_brew ffmpeg			 # Video converting
install_brew htop			 # nice top
install_brew bash-completion # Bach completion
