#!/usr/bin/env bash

source "scripts/activate.sh"


ISBREW=$(which brew)
PAD=$(padding 0)

# Brew Install Url
BREW_URL="https://raw.githubusercontent.com/Homebrew/install/master/install"


### Brew & Installation
header "# Brew"
install_brew $1
brew bundle --file=Brewfile

NWD=$(dirname $(realpath $0))
DOTS_PATH=$NWD


# Bash and Some of the tools configutation
header "# .dot files"
install_bashrc
install_dot .gitconfig
install_dot .gitignore_global
install_dot .gitattributes
install_dot .editorconfig

# Python & Tooling
header "# Python"
brew install python3 > /dev/null 2>&1
message 2 "$( printf "Python Installed: %s " "$(python3 -V)" )"
message 2 "Python Packages Installation..."
python3 -m pip install --upgrade -q pip
python3 -m pip install --upgrade -q -r requirments.txt
message 2 "Python Packages Installated:"
python3 -m pip list | awk 'NR>2 {print "\t" $0}'


# Go & Tooling
header "# Go"
brew install go  > /dev/null 2>&1
message 2 "$( printf "Go Installed: %s " "$(go version)" )"


# PHP & Tooling
header "# PHP"
brew install php  > /dev/null 2>&1
message 2 "$( printf "installed: %s " "$(php -version | head -n 1)" )"
brew bundle install --file=Brewfile.php-tools | awk '{print "\t" $0}'
# PHP Compatibility Standards
PHPCSC_GIT="https://github.com/wimg/PHPCompatibility"
PHPCSC_PATH=".php-cs/php_compatibility"
install_git_repository "${PHPCSC_GIT}" "${PHPCSC_PATH}" && checkout_last_release "${PHPCSC_PATH}"
# WordPress Code Standards
WPCS_GIT="https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards"
WPCS_PATH=".php-cs/php_wp_cs"
install_git_repository "${WPCS_GIT}" "${WPCS_PATH}" && checkout_last_release "${WPCS_PATH}"
# custom wp dev rules
MADE_PATH=".php-cs/made.ua/"
phpcs --config-set installed_paths "${NWD}/${WPCS_PATH},${NWD}/${PHPCSC_PATH},${NWD}/${MADE_PATH}" | awk '{print "\t" $0}'
# > /dev/null 2>&1


# node.js & Tooling
header "# node.js"
bew install > /dev/null 2>&1
message 2 "$( printf "installed: %s " "$(node -v)" )"


# vim settings & initial Vundle.vim
header "# vim"
brew install vim > /dev/null 2>&1
message 2 "$(vim --version | head -n 1 )"
install_dot .vimrc
install_git_repository "https://github.com/VundleVim/Vundle.vim" "vim/bundle/Vundle.vim"
vim -e -c ":PluginInstall" -c ":q" -c ":q"

header "# clouds & tools configuration"
aws configure
docker login

printf "The End!\n"
