#!/usr/bin/env bash

CWD=$(pwd)
NWD=$(realpath $(dirname $0))
# change directory
printf "# Activation Procedure Triggered \n\n";
cd "${NWD}"

source "${NWD}/bin/activate-functions.sh"

# Git Attributes
install_dot .gitconfig
install_dot .gitignore_global
install_dot .gitattributes
install_dot .gitmessage

# Actual bashrc and supported variable
install_bashrc

# vim settings & initial Vundle.vim
install_dot .vimrc
install_git_repository "https://github.com/VundleVim/Vundle.vim" \
						".vim/bundle/Vundle.vim"

# global .editorconfig
install_dot .editorconfig

# installing php tooling
install_php_tooling

# installing php tooling
install_python_tooling

# installing devops tooling
install_devops_tooling

cd "${CWD}"
