cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "homebrew/cask-fonts"

################################################################################
#  Brew's Formulas
################################################################################
[
    # BASH & GNU Compatible tooling
    "bash",
    # "shellcheck",
    "htop",
    "coreutils",
    "gnu-sed",
    "grep",
    "gnu-indent",
    "findutils",
    "gawk",
    "tree",
    "jq",
    "yq",
    "bash-completion",
    "git",
    #"git-lfs",
    "bat", # https://formulae.brew.sh/formula/bat
    "fd", # finder alternative, https://github.com/sharkdp/fd

    # "mtr",
    #"di", #  disc info https://formulae.brew.sh/formula/di

    # CLi other
    "ffmpeg",
    "media-info",

    # LOL
    "cowsay",

    # DevOps - Kubernetes
    "krew",
    "clang-format",

    # typescript/node,js
    #"deno",

    # DevOps - rest
    "dive",
    "mitmproxy",
    # "upx",

    # kube
    "helm",
    "minikube",
    "chamber",
    "docker-squash",

    # go

    "hugo",
    "octant",

    # Development
    "pre-commit",
    "ctags",
    "tmux",
    "graphviz",
    "act",
    "grpcurl",
    "golangci-lint",
    "mockery",
    "golangci-lint",
    "hey",
    "go-task",
    # "gh",

    # Clouds
    "awscli",
    # "cfn-lint",
    # "aws-shell",
    "yamllint",

    # Other hasicorp tooling
    # "consul",
    # "vault",
    # "packer",

    # Golang
    # "hugo",
    # "gotop",

].each do |pkg|
    brew pkg
end

################################################################################
#  CASK's
################################################################################
[

    # DevOps - Tooling
    "docker",
    # "virtualbox",

    # Programming - Tooling
    # "visual-studio-code",
    "sourcetree",
    "stats",

    # Fonts
    "font-fira-code",
    "font-fira-sans",
    "font-fira-mono",
    "font-jetbrains-mono",
    "font-jetbrains-mono-nerd-font",

    # Messangers
    "slack",
    "telegram-desktop",

    # DevOps
    "aws-vault",

    # Mac App Tools
    "dropbox",
    "appcleaner",
    # "istat-menus",
    "little-snitch",
    "keka",
    "iina",
    # "handbrake",
    "imageoptim",
    "google-chrome",

    # Dev
    "iterm2"
].each do |pkg|
    cask pkg
end


# Mac Applications - AppStore
mas "Apple Remote Desktop",        id: 409907375      # ARD
mas "Helium",                      id: 1054607607     # Helium
mas "Divvy - Window Manager",      id: 413857545      # Divvy
mas "Bitwarden",                   id: 1352778147     # Divvy

mas "Pandan",                      id: 1569600264     # Time awareness app
mas "MeetingsBar",                 id: 1532419400     # meetings
mas "Hidenbar",                    id: 1452453066     # hide icons

